FROM openjdk:21

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG AI_SERVICE_URL
ARG SPRING_JWT_SECRET

ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV AI_SERVICE_URL=$AI_SERVICE_URL
ENV SPRING_JWT_SECRET=$SPRING_JWT_SECRET

CMD ["./gradlew", "clean", "build"]
ARG JAR_FILE_PATH=build/libs/*.jar
COPY ${JAR_FILE_PATH} app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]